/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package BeautySalon;
import java.awt.Color;
import java.awt.Component;
import java.sql.ResultSet;

import java.awt.Image;
import java.awt.Toolkit;

import java.io.File;
import java.io.FileInputStream;
import net.proteanit.sql.DbUtils;

import java.sql.Connection;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author effel joy alquizar
 */
public class Add_services extends javax.swing.JInternalFrame {

    private String TablePages;
    private Services services;// 👈 reference to the other frame
    private String PaymentTable;
    private Payment payment;

    
    

    // Reference to the Services frame


    /**
     * Creates new form Add_services
     */
    public Add_services(Services services, Payment payment) {
          super("Add Services", true, true, true, true);
        setSize(300, 200); // Set size to make sure it is visible
    initComponents();
    this.services = services;// correctly assign reference
    this.payment = payment;
    this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
    ui.setNorthPane(null);
    // Set size to make sure it is visible
    
    
    try {
        con = connectToDatabase(); // FIXED
    } catch (Exception ex) {
        Logger.getLogger(Add_services.class.getName()).log(Level.SEVERE, null, ex);
    }

    refreshTableServicess();
}

    Connection con;
    Statement st;
    PreparedStatement pst;
 
    private static final String DbName = "bpmsdb";
    private static final String DbDriver = "com.mysql.cj.jdbc.Driver";
    private static final String DbUrl = "jdbc:mysql://localhost:3306/bpmsdb";
    private static final String DbUsername = "root";
    private static final String DbPassword = "";
  

public Connection connectToDatabase() {
    Connection con = null;
    try {
        Class.forName(DbDriver);
        con = DriverManager.getConnection(DbUrl, DbUsername, DbPassword);
        System.out.println("✅ Database connected.");
    } catch (Exception e) {
        System.out.println("❌ Database connection failed: " + e.getMessage());
        e.printStackTrace();
    }
    return con;
}


private void loadAdd_services() {
    throw new UnsupportedOperationException("Not supported yet.");
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLimage = new javax.swing.JLabel();
        jsavebrowse = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jSave = new javax.swing.JButton();
        txt_description = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDelete = new javax.swing.JButton();
        ServiceName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_prices = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableServicess = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        senddata = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1520, 870));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1520, 870));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 153)));
        jPanel4.add(jLimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 234, 174));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 250, 190));

        jsavebrowse.setBackground(new java.awt.Color(51, 102, 255));
        jsavebrowse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jsavebrowse.setForeground(new java.awt.Color(255, 255, 255));
        jsavebrowse.setText("BROWSE");
        jsavebrowse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jsavebrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsavebrowseActionPerformed(evt);
            }
        });
        jPanel2.add(jsavebrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 200, 40));

        jPanel6.setBackground(new java.awt.Color(252, 234, 252));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));

        jSave.setBackground(new java.awt.Color(102, 0, 102));
        jSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jSave.setForeground(new java.awt.Color(255, 255, 255));
        jSave.setText("ADD ");
        jSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });

        txt_description.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_description.setText("description");
        txt_description.setToolTipText("");
        txt_description.setActionCommand("<Not Set>");
        txt_description.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("DESCRIPTION :");

        jDelete.setBackground(new java.awt.Color(153, 0, 0));
        jDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jDelete.setForeground(new java.awt.Color(255, 255, 255));
        jDelete.setText("CLEAR");
        jDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        ServiceName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ServiceName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));
        ServiceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiceNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("SERVICE NAME :");

        txt_prices.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_prices.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));
        txt_prices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pricesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("COST :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txt_prices, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ServiceName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_description, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSave, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_prices, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ServiceName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_description, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 770));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 790));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));

        jLabel18.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 153));
        jLabel18.setText("   ADD SERVICES");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 910, 70));

        TableServicess.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));
        TableServicess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Service Name", "Cost", "Description", "Image"
            }
        ));
        TableServicess.setGridColor(new java.awt.Color(255, 153, 153));
        TableServicess.setShowGrid(true);
        TableServicess.setSurrendersFocusOnKeystroke(true);
        TableServicess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableServicessMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableServicess);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 910, 630));

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));

        senddata.setBackground(new java.awt.Color(204, 0, 102));
        senddata.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        senddata.setForeground(new java.awt.Color(255, 255, 255));
        senddata.setText("SAVE TO SERVICES");
        senddata.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        senddata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senddataActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("DELETE");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 594, Short.MAX_VALUE)
                .addComponent(senddata, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senddata, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 710, 910, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senddataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senddataActionPerformed
        String imagePath = null;
        String serviceName = ServiceName.getText().trim();
        String cost = txt_prices.getText().trim();
        String description = txt_description.getText().trim();
        Icon icon = jLimage.getIcon();

        if (icon != null && icon instanceof ImageIcon) {
            ImageIcon imageIcon = (ImageIcon) icon;
            imagePath = imageIcon.getDescription(); // this is the file path
        }

        if (imagePath == null || imagePath.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please upload an image.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int rowsInserted = 0;

        try (FileInputStream fis = new FileInputStream(new File(imagePath))) {
            String query = "INSERT INTO tblservices (ServiceName, Cost, Description, Image) VALUES (?, ?, ?, ?)";
            pst = con.prepareStatement(query);
            pst.setString(1, serviceName);
            pst.setString(2, cost);
            pst.setString(3, description);
            pst.setBinaryStream(4, fis, (int) new File(imagePath).length());

            rowsInserted = pst.executeUpdate();
            pst.close();

            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Service added successfully!", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                refreshTableServicess(); // your own table refresh

                // ✅ Also refresh ServicesPage JTable
                if (services != null) {
                    services.refreshTableServicess();
                    if (payment != null) {
                    payment.refreshTableServicess();
                }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_senddataActionPerformed

    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
        String imagePath = null;
        String serviceName = ServiceName.getText().trim();
        String cost = txt_prices.getText().trim();
        String description = txt_description.getText().trim();
        Icon icon = jLimage.getIcon();

        if (icon != null && icon instanceof ImageIcon) {
            ImageIcon imageIcon = (ImageIcon) icon;
            imagePath = imageIcon.getDescription(); // this is the file path
        }

        if (imagePath == null || imagePath.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please upload an image.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (FileInputStream fis = new FileInputStream(new File(imagePath))) {
            String query = "INSERT INTO tblservices (ServiceName, Cost, Description, Image) VALUES (?, ?, ?, ?)";
            pst = con.prepareStatement(query);
            pst.setString(1, serviceName);
            pst.setString(2, cost);
            pst.setString(3, description);
            pst.setBinaryStream(4, fis, (int) new File(imagePath).length());

            int rowsInserted = pst.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Service added successfully!", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                refreshTableServicess();
            }

            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
        }
        public void refreshTableServicess() {
            DefaultTableModel model = (DefaultTableModel) TableServicess.getModel();
            model.setRowCount(0);

            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bpmsdb", "root", "");
                String sql = "SELECT * FROM tblservices";
                System.out.println("con = " + con);
                System.out.println("TableServicess = " + TableServicess);

                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery(); // from java.sql.*

                while (rs.next()) {
                    byte[] imageBytes = rs.getBytes("Image");
                    ImageIcon icon = null;
                    if (imageBytes != null) {
                        Image img = Toolkit.getDefaultToolkit().createImage(imageBytes);
                        Image scaledImg = img.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
                        icon = new ImageIcon(scaledImg);
                    }

                    if (con == null) {
                        JOptionPane.showMessageDialog(null, "Database connection is not established.");
                        return;
                    }
                    if (TableServicess == null) {
                        JOptionPane.showMessageDialog(null, "TableServicess is not initialized.");
                        return;
                    }

                    model.addRow(new Object[]{
                        rs.getInt("ID"),
                        rs.getString("ServiceName"),
                        rs.getString("Cost"),
                        rs.getString("Description"),
                        icon
                            
                    });
                }
                

                rs.close();
                pst.close();

            } catch (Exception e) {
                e.printStackTrace(); // 👈 This is important to reveal full error
                JOptionPane.showMessageDialog(null, "Error loading services: " + e.getMessage());
            }

            // Set row height and cell renderer for image column (index 6)
            TableServicess.setRowHeight(100);
            TableServicess.getColumnModel().getColumn(4).setCellRenderer(new DefaultTableCellRenderer() {
                @Override
                public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {
                    if (value instanceof ImageIcon) {
                        setIcon((ImageIcon) value);
                        setText("");
                    } else {
                        setIcon(null);
                        setText("No Image");
                    }
                    return this;
                }
            });
            
    }//GEN-LAST:event_jSaveActionPerformed

    private void jsavebrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsavebrowseActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();

        if (f != null) {
            String filename = f.getAbsolutePath();
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename)
                .getImage().getScaledInstance(jLimage.getWidth(), jLimage.getHeight(), Image.SCALE_SMOOTH));
            imageIcon.setDescription(filename); // Store path for later use
            jLimage.setIcon(imageIcon);
        } else {
            JOptionPane.showMessageDialog(null, "No image selected!");
        }
    }//GEN-LAST:event_jsavebrowseActionPerformed

    private void ServiceNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiceNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiceNameActionPerformed

    private void TableServicessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableServicessMouseClicked
         int selectedRow = TableServicess.getSelectedRow();
if (selectedRow >= 0) {
  

    String service = TableServicess.getValueAt(selectedRow, 1).toString();
    String cost = TableServicess.getValueAt(selectedRow, 2).toString();
    String about = TableServicess.getValueAt(selectedRow, 3).toString();

  
   
    ServiceName.setText(service);
    txt_prices.setText(cost);
    txt_description.setText(about);


    Object imageObject = TableServicess.getValueAt(selectedRow, 4);
    if (imageObject instanceof ImageIcon) {
        ImageIcon icon = (ImageIcon) imageObject;
        Image img = icon.getImage();
        int width = jLimage.getWidth() > 0 ? jLimage.getWidth() : 120;
        int height = jLimage.getHeight() > 0 ? jLimage.getHeight() : 120;

        Image scaledImg = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImg);

        jLimage.setHorizontalAlignment(SwingConstants.CENTER);
        jLimage.setVerticalAlignment(SwingConstants.CENTER);
        jLimage.setIcon(scaledIcon);
        jLimage.setText(""); 
    } else {
        jLimage.setIcon(null);
        jLimage.setText("No Image");
    }
}

    }//GEN-LAST:event_TableServicessMouseClicked

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
         int response = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to clear the items?",
        "Confirm Clear",
        JOptionPane.OK_CANCEL_OPTION,
        JOptionPane.WARNING_MESSAGE
);

if (response == JOptionPane.OK_OPTION) {
    
    ServiceName.setText("");
    txt_prices.setText("");
    txt_description.setText("");
    jLimage.setIcon(null);
}
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = TableServicess.getSelectedRow();

if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Please select an item to delete.");
    return;
}

int response = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete the selected item?",
        "Confirm Delete",
        JOptionPane.OK_CANCEL_OPTION,
        JOptionPane.WARNING_MESSAGE
);

if (response == JOptionPane.OK_OPTION) {
    try {
        // Get the selected service ID from the table (assuming it's in the first column)
        int serviceId = (int) TableServicess.getValueAt(selectedRow, 0);

        // Delete from the database
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bpmsdb", "root", "");
        String deleteQuery = "DELETE FROM tblservices WHERE ID = ?";
        PreparedStatement pstmt = con.prepareStatement(deleteQuery);
        pstmt.setInt(1, serviceId);

        int rowsAffected = pstmt.executeUpdate();

        if (rowsAffected > 0) {
            // Remove from JTable
            DefaultTableModel model = (DefaultTableModel) TableServicess.getModel();
            model.removeRow(selectedRow);

            // Clear form fields
            ServiceName.setText("");
            txt_prices.setText("");
            txt_description.setText("");
            jLimage.setIcon(null);

            JOptionPane.showMessageDialog(this, "Item deleted successfully.");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to delete item from database.");
        }

        pstmt.close();
        con.close();

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
    }
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_pricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pricesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pricesActionPerformed
private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
    refreshTableServicess();
    refreshTablePages();
    refreshPaymentTable();
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ServiceName;
    private javax.swing.JTable TableServicess;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLimage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jsavebrowse;
    private javax.swing.JButton senddata;
    private javax.swing.JTextField txt_description;
    private javax.swing.JTextField txt_prices;
    // End of variables declaration//GEN-END:variables

    private void refreshTablePages() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void refreshPaymentTable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


}
