    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BeautySalon;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JLayeredPane;
import javax.swing.Timer;
import javax.swing.plaf.basic.BasicInternalFrameUI;
/**
 *
 * @author effel joy alquizar
 */
public class AdminDashboard extends javax.swing.JFrame {
   // In AdminDashboard or wherever you're opening the JInternalFrames:

boolean isSidebarCollapsed = false;
    private Timer sidebarTimer;// Declare this at class level (top of your class)
  Color DefaultColor,ClickedColor;


    // pass reference

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
      Image img = new ImageIcon(getClass().getResource("/images/logo.jpg")).getImage();
    
    // Set the icon image for the JFrame
    this.setIconImage(img);
          DefaultColor=new Color(253,235,235);
        ClickedColor=new Color(255,153,204);
        Profile.setBackground(DefaultColor);
        Home1.setBackground(DefaultColor);
        Services.setBackground(DefaultColor);
        Appointment.setBackground(DefaultColor);
         bookinglist.setBackground(DefaultColor);
        Paymentss.setBackground(DefaultColor);
         client.setBackground(DefaultColor);
       specialist.setBackground(DefaultColor);
      

        jdesktopPane1 = new JDesktopPane();
    jdesktopPane2 = new JDesktopPane();

        
       
    }
        
Services services = new Services();
Payment payment = new Payment();
Add_services addServices = new Add_services(services,payment);
private JDesktopPane jdesktopPane1;
private JDesktopPane jdesktopPane2;



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sidebarjPanel4 = new javax.swing.JPanel();
        specialist = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Home1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Paymentss = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Services = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Appointment = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        client = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Profile = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        bookinglist = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserIcon/menus.png"))); // NOI18N
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 80));

        jPanel2.setBackground(new java.awt.Color(153, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("BGLAM ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 204, 0));
        jLabel15.setText("Your beauty, your style");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 1450, 80));

        sidebarjPanel4.setBackground(new java.awt.Color(51, 51, 51));
        sidebarjPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        specialist.setBackground(new java.awt.Color(252, 235, 235));
        specialist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                specialistMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                specialistMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 102));
        jLabel8.setText("OUR STYLIST");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        javax.swing.GroupLayout specialistLayout = new javax.swing.GroupLayout(specialist);
        specialist.setLayout(specialistLayout);
        specialistLayout.setHorizontalGroup(
            specialistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialistLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        specialistLayout.setVerticalGroup(
            specialistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, specialistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
        );

        sidebarjPanel4.add(specialist, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 180, 30));

        Home1.setBackground(new java.awt.Color(252, 235, 235));
        Home1.setForeground(new java.awt.Color(255, 0, 204));
        Home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Home1MousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 102));
        jLabel1.setText("DASHBOARD");

        javax.swing.GroupLayout Home1Layout = new javax.swing.GroupLayout(Home1);
        Home1.setLayout(Home1Layout);
        Home1Layout.setHorizontalGroup(
            Home1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Home1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(39, 39, 39))
        );
        Home1Layout.setVerticalGroup(
            Home1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Home1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        sidebarjPanel4.add(Home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 180, 30));

        Paymentss.setBackground(new java.awt.Color(252, 235, 235));
        Paymentss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaymentssMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PaymentssMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 102));
        jLabel3.setText("payment");

        javax.swing.GroupLayout PaymentssLayout = new javax.swing.GroupLayout(Paymentss);
        Paymentss.setLayout(PaymentssLayout);
        PaymentssLayout.setHorizontalGroup(
            PaymentssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentssLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        PaymentssLayout.setVerticalGroup(
            PaymentssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentssLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebarjPanel4.add(Paymentss, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 180, 30));

        Services.setBackground(new java.awt.Color(252, 235, 235));
        Services.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ServicesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ServicesMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 102));
        jLabel2.setText("SERVICES");

        javax.swing.GroupLayout ServicesLayout = new javax.swing.GroupLayout(Services);
        Services.setLayout(ServicesLayout);
        ServicesLayout.setHorizontalGroup(
            ServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServicesLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        ServicesLayout.setVerticalGroup(
            ServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServicesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        sidebarjPanel4.add(Services, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 180, 30));

        Appointment.setBackground(new java.awt.Color(252, 235, 235));
        Appointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AppointmentMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AppointmentMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 102));
        jLabel4.setText("APPOINTMENT");

        javax.swing.GroupLayout AppointmentLayout = new javax.swing.GroupLayout(Appointment);
        Appointment.setLayout(AppointmentLayout);
        AppointmentLayout.setHorizontalGroup(
            AppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppointmentLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        AppointmentLayout.setVerticalGroup(
            AppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppointmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebarjPanel4.add(Appointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 180, 30));

        client.setBackground(new java.awt.Color(252, 235, 235));
        client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clientMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 102));
        jLabel5.setText("CLIENT");

        javax.swing.GroupLayout clientLayout = new javax.swing.GroupLayout(client);
        client.setLayout(clientLayout);
        clientLayout.setHorizontalGroup(
            clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        clientLayout.setVerticalGroup(
            clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebarjPanel4.add(client, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 180, 30));

        Profile.setBackground(new java.awt.Color(252, 235, 235));
        Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProfileMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 102));
        jLabel6.setText("PROFILE");

        javax.swing.GroupLayout ProfileLayout = new javax.swing.GroupLayout(Profile);
        Profile.setLayout(ProfileLayout);
        ProfileLayout.setHorizontalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        ProfileLayout.setVerticalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        sidebarjPanel4.add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 180, 30));

        jPanel8.setBackground(new java.awt.Color(252, 235, 235));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel8MousePressed(evt);
            }
        });

        bookinglist.setBackground(new java.awt.Color(252, 235, 235));
        bookinglist.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        bookinglist.setForeground(new java.awt.Color(153, 0, 102));
        bookinglist.setText("invoice");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(bookinglist)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(bookinglist, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sidebarjPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 180, 30));

        jButton1.setBackground(new java.awt.Color(204, 0, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOG OUT");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        sidebarjPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 180, 30));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("admin@gmail.com");
        sidebarjPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("admin");
        sidebarjPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserIcon/man.png"))); // NOI18N
        sidebarjPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 130, 140));

        jPanel1.add(sidebarjPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 240, 790));

        jPanel13.setBackground(new java.awt.Color(246, 237, 237));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(255, 204, 204));

        jLabel24.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 153));
        jLabel24.setText("ADMIN DASHBOARD");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(350, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(345, 345, 345))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel24)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(153, 0, 102));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("SPECIALIST");
        jLabel18.setOpaque(true);
        jPanel21.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 110));

        jLabel19.setBackground(new java.awt.Color(51, 102, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("6");
        jLabel19.setOpaque(true);
        jPanel21.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 0, 130, 100));

        jPanel15.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 330, 110));

        jPanel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(102, 102, 0));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("SERVICES");
        jLabel20.setOpaque(true);
        jPanel22.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 233, 110));

        jLabel21.setBackground(new java.awt.Color(102, 0, 102));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("50");
        jLabel21.setOpaque(true);
        jPanel22.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 0, 110, 100));

        jPanel15.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 340, 110));

        jPanel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setBackground(new java.awt.Color(153, 0, 0));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("SALES");
        jLabel22.setOpaque(true);
        jPanel23.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 209, 110));

        jLabel23.setBackground(new java.awt.Color(255, 153, 51));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("789");
        jLabel23.setOpaque(true);
        jPanel23.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 0, 110, 100));

        jPanel15.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 310, 110));

        jPanel13.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 1130, 150));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(102, 102, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("APPOINTMENT");
        jLabel13.setOpaque(true);
        jPanel18.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 110));

        jLabel14.setBackground(new java.awt.Color(102, 0, 102));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("15");
        jLabel14.setOpaque(true);
        jPanel18.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 110, 100));

        jPanel16.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 340, 110));

        jPanel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(153, 0, 102));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("CUSTOMER");
        jLabel11.setOpaque(true);
        jPanel19.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 110));

        jLabel12.setBackground(new java.awt.Color(102, 153, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("10");
        jLabel12.setOpaque(true);
        jPanel19.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 120, 100));

        jPanel16.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 330, 110));

        jPanel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(153, 51, 0));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("BOOKED");
        jLabel16.setOpaque(true);
        jPanel20.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 110));

        jLabel17.setBackground(new java.awt.Color(255, 153, 0));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("15");
        jLabel17.setOpaque(true);
        jPanel20.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 0, 100, 100));

        jPanel16.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, -1, 110));

        jPanel13.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 1130, 150));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel17.add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 24, 429, 207));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("NOTES ");
        jPanel17.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 43, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel17.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 630, 190));

        jPanel13.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 1140, 250));

        jDesktopPane2.setLayer(jPanel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 1280, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        RegisterAdmin registeradmin = new RegisterAdmin();
        registeradmin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jPanel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MousePressed
        Profile.setBackground(DefaultColor);
        Home1.setBackground(DefaultColor);
        Services.setBackground(DefaultColor);
        Appointment.setBackground(DefaultColor);
        bookinglist.setBackground(ClickedColor);
        Paymentss.setBackground(DefaultColor);
        client.setBackground(DefaultColor);
        specialist.setBackground(DefaultColor);

    }//GEN-LAST:event_jPanel8MousePressed

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        BookingList bookinglist = new  BookingList();
        jDesktopPane2.removeAll();

        // Set Profile size to match jDesktopPane1
        int width = jDesktopPane2.getWidth();
        int height = jDesktopPane2.getHeight();

        jDesktopPane2.add(bookinglist, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, width, height));
        bookinglist.setVisible(true);
        jDesktopPane2.repaint();
        jDesktopPane2.revalidate();
    }//GEN-LAST:event_jPanel8MouseClicked

    private void ProfileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileMousePressed
        Profile.setBackground(ClickedColor);
        Home1.setBackground(DefaultColor);
        Services.setBackground(DefaultColor);
        Appointment.setBackground(DefaultColor);
        bookinglist.setBackground(DefaultColor);
        Paymentss.setBackground(DefaultColor);
        client.setBackground(DefaultColor);
        specialist.setBackground(DefaultColor);

    }//GEN-LAST:event_ProfileMousePressed

    private void ProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileMouseClicked
        AdminProfile adminProfile= new  AdminProfile();
        jDesktopPane2.removeAll();

        // Set Profile size to match jDesktopPane1
        int width = jDesktopPane2.getWidth();
        int height = jDesktopPane2.getHeight();

        jDesktopPane2.add(adminProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, width, height));
        adminProfile.setVisible(true);
        jDesktopPane2.repaint();
        jDesktopPane2.revalidate();
    }//GEN-LAST:event_ProfileMouseClicked

    private void clientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientMousePressed
        Profile.setBackground(DefaultColor);
        Home1.setBackground(DefaultColor);
        Services.setBackground(DefaultColor);
        Appointment.setBackground(DefaultColor);
        bookinglist.setBackground(DefaultColor);
        Paymentss.setBackground(DefaultColor);
        client.setBackground(ClickedColor);
        specialist.setBackground(DefaultColor);

    }//GEN-LAST:event_clientMousePressed

    private void clientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientMouseClicked
        Add_client client = new  Add_client();
        jDesktopPane2.removeAll();

        // Set Profile size to match jDesktopPane1
        int width = jDesktopPane2.getWidth();
        int height = jDesktopPane2.getHeight();

        jDesktopPane2.add(client, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, width, height));
        client.setVisible(true);
        jDesktopPane2.repaint();
        jDesktopPane2.revalidate();
    }//GEN-LAST:event_clientMouseClicked

    private void AppointmentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppointmentMousePressed
        Profile.setBackground(DefaultColor);
        Home1.setBackground(DefaultColor);
        Services.setBackground(DefaultColor);
        Appointment.setBackground(ClickedColor);
        bookinglist.setBackground(DefaultColor);
        Paymentss.setBackground(DefaultColor);
        client.setBackground(DefaultColor);
        specialist.setBackground(DefaultColor);

    }//GEN-LAST:event_AppointmentMousePressed

    private void AppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppointmentMouseClicked
        Add_appointment appointment = new  Add_appointment();
        jDesktopPane2.removeAll();

        // Set Profile size to match jDesktopPane1
        int width = jDesktopPane2.getWidth();
        int height = jDesktopPane2.getHeight();

        jDesktopPane2.add(appointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, width, height));
        appointment.setVisible(true);
        jDesktopPane2.repaint();
        jDesktopPane2.revalidate();
    }//GEN-LAST:event_AppointmentMouseClicked

    private void ServicesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServicesMousePressed
        Profile.setBackground(DefaultColor);
        Home1.setBackground(DefaultColor);
        Services.setBackground(ClickedColor);
        Appointment.setBackground(DefaultColor);
        bookinglist.setBackground(DefaultColor);
        Paymentss.setBackground(DefaultColor);
        client.setBackground(DefaultColor);
        specialist.setBackground(DefaultColor);

    }//GEN-LAST:event_ServicesMousePressed

    private void ServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServicesMouseClicked
        if (jdesktopPane1 == null) {
            jdesktopPane1 = new JDesktopPane();
        }
        if (jdesktopPane2 == null) {
            jdesktopPane2 = new JDesktopPane();
        }

        // Initialize the Services and Add_services internal frames
        Services services = new Services();
        Payment payment = new Payment();
        Add_services addServices = new Add_services(services,payment);

        jdesktopPane1.add(new Services());
        jdesktopPane2.add(new Payment());
        jdesktopPane2.add(addServices);

        // Set internal frames to visible
        services.setVisible(true);
        payment.setVisible(true);
        addServices.setVisible(true);
        int width = jDesktopPane2.getWidth();
        int height = jDesktopPane2.getHeight();

        jDesktopPane2.add(addServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, width, height));
        addServices.setVisible(true);
        jDesktopPane2.repaint();
        jDesktopPane2.revalidate();

        try {
            addServices.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ServicesMouseClicked

    private void PaymentssMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentssMousePressed
        Profile.setBackground(DefaultColor);
        Home1.setBackground(DefaultColor);
        Services.setBackground(DefaultColor);
        Appointment.setBackground(DefaultColor);
        bookinglist.setBackground(DefaultColor);
        Paymentss.setBackground(ClickedColor);
        client.setBackground(DefaultColor);
        specialist.setBackground(DefaultColor);

    }//GEN-LAST:event_PaymentssMousePressed

    private void PaymentssMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentssMouseClicked

        jDesktopPane2.removeAll();

        // Create a single instance
        Payment payment = new Payment();

        // Set its size and location
        int width = jDesktopPane2.getWidth();
        int height = jDesktopPane2.getHeight();
        payment.setBounds(0, 0, width, height);

        // Add to the desktop pane
        jDesktopPane2.add(payment);
        payment.setVisible(true);

        try {
            payment.setSelected(true); // bring it to front
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }

        jDesktopPane2.repaint();
        jDesktopPane2.revalidate();

    }//GEN-LAST:event_PaymentssMouseClicked

    private void Home1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home1MousePressed
        Profile.setBackground(DefaultColor);
        Home1.setBackground(ClickedColor);
        Services.setBackground(DefaultColor);
        Appointment.setBackground(DefaultColor);
        bookinglist.setBackground(DefaultColor);
        Paymentss.setBackground(DefaultColor);
        client.setBackground(DefaultColor);
        specialist.setBackground(DefaultColor);

    }//GEN-LAST:event_Home1MousePressed

    private void Home1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home1MouseClicked
        Dashboard dashboard= new  Dashboard();
        jDesktopPane2.removeAll();

        // Set Profile size to match jDesktopPane1
        int width = jDesktopPane2.getWidth();
        int height = jDesktopPane2.getHeight();

        jDesktopPane2.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, width, height));
        dashboard.setVisible(true);
        jDesktopPane2.repaint();
        jDesktopPane2.revalidate();
    }//GEN-LAST:event_Home1MouseClicked

    private void specialistMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_specialistMousePressed
        

    }//GEN-LAST:event_specialistMousePressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        Add_specialist specialist = new  Add_specialist();
        jDesktopPane2.removeAll();

        // Set Profile size to match jDesktopPane1
        int width = jDesktopPane2.getWidth();
        int height = jDesktopPane2.getHeight();

        jDesktopPane2.add(specialist, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, width, height));
        specialist.setVisible(true);
        jDesktopPane2.repaint();
        jDesktopPane2.revalidate();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        final int fullWidth = 200;
    final int collapsedWidth = 60;
    final int delay = 5; // milliseconds
    final int step = 10;

    if (sidebarTimer != null && sidebarTimer.isRunning()) return; // prevent double trigger

    sidebarTimer = new Timer(delay, null);

    sidebarTimer.addActionListener(new ActionListener() {
        int width = sidebarjPanel4.getWidth();

        public void actionPerformed(ActionEvent e) {
            if (!isSidebarCollapsed) {
                // Collapse
                if (width > collapsedWidth) {
                    width -= step;
                    sidebarjPanel4.setPreferredSize(new Dimension(width, sidebarjPanel4.getHeight()));
                    sidebarjPanel4.revalidate();
                } else {
                    sidebarTimer.stop();
                    isSidebarCollapsed = true;

                    // Hide components after collapsing
                    jLabel27.setVisible(false);
                    jLabel7.setVisible(false);
                     jLabel9.setVisible(false);
                    Profile.setVisible(false);
                    Home1.setVisible(false);
                    Paymentss.setVisible(false);
                    jPanel8.setVisible(false);
                    client.setVisible(false);
                    Services.setVisible(false);
                    Appointment.setVisible(false);
                    specialist.setVisible(false);
                }
            } else {
                // Expand
                if (width < fullWidth) {
                    width += step;
                    sidebarjPanel4.setPreferredSize(new Dimension(width, sidebarjPanel4.getHeight()));
                    sidebarjPanel4.revalidate();
                } else {
                    sidebarTimer.stop();
                    isSidebarCollapsed = false;

                    // Show components after expanding
                   jLabel27.setVisible(true);
                    jLabel7.setVisible(true);
                     jLabel9.setVisible(true);
                    Profile.setVisible(true);
                    Home1.setVisible(true);
                    Paymentss.setVisible(true);
                    jPanel8.setVisible(true);
                    client.setVisible(true);
                    Services.setVisible(true);
                    Appointment.setVisible(true);
                    specialist.setVisible(true);
                }
            }

            sidebarjPanel4.repaint();
        }
    });

    sidebarTimer.start();


    }//GEN-LAST:event_jLabel26MouseClicked

    private void specialistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_specialistMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_specialistMouseClicked

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        // TODO add your handling code here:Profile.setBackground(DefaultColor);
        Home1.setBackground(DefaultColor);
        Services.setBackground(DefaultColor);
        Appointment.setBackground(DefaultColor);
        bookinglist.setBackground(DefaultColor);
        Paymentss.setBackground(DefaultColor);
        client.setBackground(DefaultColor);
        specialist.setBackground(ClickedColor);
    }//GEN-LAST:event_jLabel8MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Appointment;
    private javax.swing.JPanel Home1;
    private javax.swing.JPanel Paymentss;
    private javax.swing.JPanel Profile;
    private javax.swing.JPanel Services;
    private javax.swing.JLabel bookinglist;
    private javax.swing.JPanel client;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel sidebarjPanel4;
    private javax.swing.JPanel specialist;
    // End of variables declaration//GEN-END:variables

    private static class desktopPane {

       

        private static void add(Add_services addServices) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public desktopPane() {
        }
    }
}
