/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BeautySalon;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author effel joy alquizar
 */
public class BookingSummaryFrame extends javax.swing.JFrame {

 private static String serviceName, bookingDate, bookingTime, unitCost, quantity, specialist;   
 public static String getServiceName() {
    return serviceName;
}

public static String getBookingDate() {
    return bookingDate;
}

public static String getBookingTime() {
    return bookingTime;
}

public static String getUnitCost() {
    return unitCost;
}

public static String getQuantity() {
    return quantity;
}

public static String getSpecialist() {
    return specialist;
}


    
public BookingSummaryFrame(String no, String service, String cost, String about, Icon image,
                           String date, String time, int quantity, String specialist ,int total) {

        initComponents();
        Image img = new ImageIcon(getClass().getResource("/images/logo.jpg")).getImage();
    
    // Set the icon image for the JFrame
    this.setIconImage(img);
        lblNo.setText(no);
    lblService.setText(service);
    lblCost.setText(cost);
    lblAbout.setText(about);
    lblImage.setIcon(image);

    lblDate.setText(date);
    lblTime.setText(time);
    lblQuantity.setText(String.valueOf(quantity));
    lspecialist.setText(specialist);
    lblTotal.setText("₱" + total);

    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblService = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblAbout = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblCost = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        payment = new javax.swing.JComboBox<>();
        btnBook = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lblQuantity = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lspecialist = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNo = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1029, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1236, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(1520, 870));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 102), 2));

        jLabel19.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 153));
        jLabel19.setText("BOOKING INFORMATION");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 0, 0));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText(" X ");
        jLabel39.setOpaque(true);
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel39MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(244, 244, 244))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 140));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblImage.setBackground(new java.awt.Color(255, 255, 255));
        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 102), 2, true));
        lblImage.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 270, 210));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));
        jPanel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblService.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        lblService.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblService.setText("xCszc\\");

            javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
            jPanel7.setLayout(jPanel7Layout);
            jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(lblService, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(91, Short.MAX_VALUE))
            );
            jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblService, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
            );

            jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 350, -1));

            lblAbout.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
            lblAbout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblAbout.setText("jLabel5");
            lblAbout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));
            lblAbout.setOpaque(true);

            javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
            jPanel8.setLayout(jPanel8Layout);
            jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
            );
            jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
            );

            jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 460, -1));

            jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));
            jPanel9.setEnabled(false);

            lblCost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            lblCost.setForeground(new java.awt.Color(255, 0, 0));
            lblCost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblCost.setText("jLabel3");

            javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
            jPanel9.setLayout(jPanel9Layout);
            jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(lblCost, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE))
            );
            jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblCost, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            );

            jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 200, 40));

            jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));
            jPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

            lblDate.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
            lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblDate.setText("jLabel6");
            lblDate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            lblDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

            javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
            jPanel10.setLayout(jPanel10Layout);
            jPanel10Layout.setHorizontalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(87, Short.MAX_VALUE))
            );
            jPanel10Layout.setVerticalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            );

            jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 350, 40));

            jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));

            lblTime.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
            lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblTime.setText("jLabel7");

            javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
            jPanel11.setLayout(jPanel11Layout);
            jPanel11Layout.setHorizontalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                    .addContainerGap(106, Short.MAX_VALUE)
                    .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(103, 103, 103))
            );
            jPanel11Layout.setVerticalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addContainerGap())
            );

            jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 350, 40));

            jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));

            lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            lblTotal.setForeground(new java.awt.Color(204, 0, 0));
            lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblTotal.setText("jLabel8");

            javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
            jPanel12.setLayout(jPanel12Layout);
            jPanel12Layout.setHorizontalGroup(
                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                    .addContainerGap(97, Short.MAX_VALUE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(73, 73, 73))
            );
            jPanel12Layout.setVerticalGroup(
                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            );

            jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 350, 40));

            payment.setBackground(new java.awt.Color(242, 242, 242));
            payment.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
            payment.setForeground(new java.awt.Color(0, 0, 204));
            payment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gcash Payment", "Card Payment" }));
            payment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));
            payment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            payment.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    paymentActionPerformed(evt);
                }
            });
            jPanel4.add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 350, 40));

            btnBook.setBackground(new java.awt.Color(153, 0, 102));
            btnBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            btnBook.setForeground(new java.awt.Color(255, 255, 255));
            btnBook.setText("CONTINUE  PAYMENT");
            btnBook.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnBookActionPerformed(evt);
                }
            });
            jPanel4.add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, 350, 40));

            jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel9.setText("DESCRIPTION : ");
            jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

            jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel10.setText("TIME :");
            jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, 20));

            jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel11.setText("QUANTITY :");
            jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, -1, -1));

            jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel12.setText("SELECT PAYMENT METHOD :");
            jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, -1, -1));

            jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel13.setText("TOTAL :");
            jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, -1, -1));

            jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));
            jPanel13.setForeground(new java.awt.Color(255, 0, 0));

            lblQuantity.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
            lblQuantity.setForeground(new java.awt.Color(204, 0, 0));
            lblQuantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblQuantity.setText("jLabel1");

            javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
            jPanel13.setLayout(jPanel13Layout);
            jPanel13Layout.setHorizontalGroup(
                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                    .addContainerGap(145, Short.MAX_VALUE)
                    .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(142, 142, 142))
            );
            jPanel13Layout.setVerticalGroup(
                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addContainerGap())
            );

            jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 350, 40));

            jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 2));

            lspecialist.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
            lspecialist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lspecialist.setText("jLabel1");

            javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
            jPanel14.setLayout(jPanel14Layout);
            jPanel14Layout.setHorizontalGroup(
                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                    .addContainerGap(82, Short.MAX_VALUE)
                    .addComponent(lspecialist, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(66, 66, 66))
            );
            jPanel14Layout.setVerticalGroup(
                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lspecialist, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            );

            jPanel4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 350, 40));

            jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel1.setText("STYLIST :");
            jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, -1));

            lblNo.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
            lblNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jPanel4.add(lblNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 37, 40));

            jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel14.setText("DATE :");
            jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

            jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel15.setText("COST :");
            jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

            jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel16.setText("SERVICE NAME :");
            jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserIcon/booking.png"))); // NOI18N
            jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 50, 180, 150));

            jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 1180, 630));

            jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel38.setText(" X ");
            jLabel38.setOpaque(true);
            jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 30, 20));

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1220, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
    // Booking information to pass
    String serviceName = lblService.getText();
    String bookingDate = lblDate.getText();
    String bookingTime = lblTime.getText();
    String unitCost = lblCost.getText();
    String quantity = lblQuantity.getText();
    String specialist = lspecialist.getText();
    String total = lblTotal.getText();

    // Get selected payment method
    String selectedMethod = payment.getSelectedItem().toString();

    if (selectedMethod.equals("Gcash Payment")) {
        GcashPayment gcash = new GcashPayment(serviceName, bookingDate, bookingTime, unitCost, quantity, specialist, total);
        gcash.setLocationRelativeTo(null); 
        gcash.setVisible(true);
        this.dispose(); // Close current window only after opening payment window

    } else if (selectedMethod.equals("Card Payment")) {
        Cardpayment card = new Cardpayment(serviceName, bookingDate, bookingTime, unitCost, quantity, specialist, total);
        card.setLocationRelativeTo(null); 
        card.setVisible(true);
        this.dispose();

    } else {
        JOptionPane.showMessageDialog(null, "Please select a valid payment method.");
    }




    }//GEN-LAST:event_btnBookActionPerformed

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
      
    }//GEN-LAST:event_paymentActionPerformed

    private void jLabel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel39MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingSummaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingSummaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingSummaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingSummaryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
   
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Provide sample/test data
            String no = "001";
            String service = "Nail Cleaning";
            String cost = "₱150";
            String about = "Basic nail grooming service.";
            Icon image = new ImageIcon("path/to/default/image.jpg"); // Optional: test image
            String date = "2025-05-08";
            String time = "10:00 AM";
            int quantity = 2;
            String specialist = "";
            int total = 300;

            new BookingSummaryFrame(no, service, cost, about, image, date, time, quantity, specialist,total).setVisible(true);
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblService;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lspecialist;
    private javax.swing.JComboBox<String> payment;
    // End of variables declaration//GEN-END:variables

    private void bookNow() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void ProcessBooking(String over_the_Counter) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void insertBookingIntoDatabase(String bookingNo, String no, String service, String cost, String about, String date, String time, int quantity, String total, String method, String method1, ImageIcon image) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
