/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package BeautySalon;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Insets;
import java.io.File;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author effel joy alquizar
 */
public class BookingList extends javax.swing.JInternalFrame {
   
 // ✅ Reference to Services

    public BookingList() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
    ui.setNorthPane(null);
    refreshTableBooking();
       
    
    }

 



    /**
     * Creates new form Pages


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBooking = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1526, 871));

        jPanel1.setPreferredSize(new java.awt.Dimension(1526, 871));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 270, 30));

        jButton1.setBackground(new java.awt.Color(204, 0, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 30, 110, 30));

        jLabel18.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 153));
        jLabel18.setText("BOOKING LIST");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 80));

        TableBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Booking No.", "Client Name", "Service Name", "Number Info", "Book Date", "Book Time", "Unit Cost", "Quantity", "Stylist", "Payment"
            }
        ));
        TableBooking.setGridColor(new java.awt.Color(255, 153, 153));
        TableBooking.setRowHeight(30);
        TableBooking.setShowGrid(true);
        TableBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableBookingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableBooking);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1310, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableBookingMouseClicked
       
    int row = TableBooking.getSelectedRow();

    if (row != -1) {
        String bookingNo = TableBooking.getValueAt(row, 1).toString();
        String clientName = TableBooking.getValueAt(row, 2).toString();
        String serviceName = TableBooking.getValueAt(row, 3).toString();
        String numberInfo = TableBooking.getValueAt(row, 4).toString();
        String bookDate = TableBooking.getValueAt(row, 5).toString();
        String bookTime = TableBooking.getValueAt(row, 6).toString();
        String unitCost = TableBooking.getValueAt(row, 7).toString();
        String quantity = TableBooking.getValueAt(row, 8).toString();
        String specialist = TableBooking.getValueAt(row, 9).toString();
        String payment = TableBooking.getValueAt(row, 10).toString();

        // Calculate total (unitCost * quantity)
        double totalCost = Double.parseDouble(unitCost) * Integer.parseInt(quantity);
        String total = String.format("%.2f", totalCost);

        // For now, set cash and balance to "0.00" or some placeholder value
        String cash = "0.00";
        String balance = "0.00";

        // Create and show the RecieptsWindow
        RecieptsWindow recieptsWindow = new RecieptsWindow(
            bookingNo, clientName, numberInfo,
            serviceName, bookDate, bookTime,
            unitCost, quantity, total,
            payment, specialist,
            cash, balance
        );
        recieptsWindow.setLocationRelativeTo(null); // Center the pop-up on screen

        recieptsWindow.setVisible(true);
       
    }
    

    
    }//GEN-LAST:event_TableBookingMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String search = searchField.getText(); // your actual search field
DefaultTableModel model = (DefaultTableModel) TableBooking.getModel();
model.setRowCount(0); // clear previous results

// Expanded search: id, booking_number, client_name, service_name, etc.
String query = "SELECT * FROM bookinglist WHERE " +
               "CAST(id AS CHAR) LIKE ? OR " +
               "booking_number LIKE ? OR " +
               "client_name LIKE ? OR " +
               "service_name LIKE ?";

try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bpmsdb", "root", "");
     PreparedStatement pst = con.prepareStatement(query)) {

    // Set same search text for all parameters
    for (int i = 1; i <= 4; i++) {
        pst.setString(i, "%" + search + "%");
    }

            java.sql.ResultSet rs = pst.executeQuery();

    while (rs.next()) {
        int id = rs.getInt("id");
        String booking_no = rs.getString("booking_number");
        String client_name = rs.getString("client_name");
        String numberinfo = rs.getString("numberinfo");
        String service_name = rs.getString("service_name");
        String booking_date = rs.getString("booking_date");
        String booking_time = rs.getString("booking_time");
        double unit_cost = rs.getDouble("unit_cost");
        int quantity = rs.getInt("quantity");
        String specialist = rs.getString("specialist");
        String payment_method = rs.getString("payment_method");

        model.addRow(new Object[]{
            id, booking_no, client_name, numberinfo, service_name,
            booking_date, booking_time, unit_cost, quantity, specialist, payment_method
        });
    }

} catch (SQLException ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "Search failed: " + ex.getMessage());
}

    }//GEN-LAST:event_jButton1ActionPerformed
private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {
    refreshTableBooking();
}

public void refreshTableBooking() {
    DefaultTableModel model = (DefaultTableModel) TableBooking.getModel();
    model.setRowCount(0); // Clear table

    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bpmsdb", "root", "");
        String sql = "SELECT * FROM bookinglist";
        PreparedStatement pst = con.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("booking_number"),
                rs.getString("client_name"),
                rs.getString("service_name"),
                rs.getString("numberinfo"),
                rs.getDate("booking_date"),
                rs.getString("booking_time"),
                rs.getString("unit_cost"),
                rs.getString("quantity"),
                rs.getString("specialist"),
                rs.getString("payment_method"),
                rs.getString("Total_cost"),
                rs.getString("receptionist"),
                rs.getString("cash"),
                rs.getString("balance")
            });
        }

        rs.close();
        pst.close();
        con.close();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Failed to load bookings.");
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTable TableBooking;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }



  




   

  
}
