/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BeautySalon;

import java.awt.Color;
import java.awt.Image;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author effel joy alquizar
 */
public class Client extends javax.swing.JFrame {
   
       Connection con;
    Statement st;
    PreparedStatement pst;
    /**
     * Creates new form Client
     */
    public Client() {
      initComponents();
      Image img = new ImageIcon(getClass().getResource("/images/logo.jpg")).getImage();
    
    // Set the icon image for the JFrame
    this.setIconImage(img);
        try {
            Connection();
        } catch (SQLException ex) {
            Logger.getLogger(RegisterClient.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setLocationRelativeTo(null);
    }
    
    private static final String DbName = "bpmsdb";
    private static final String DbDriver = "com.mysql.cj.jdbc.Driver";
    private static final String DbUrl = "jdbc:mysql://localhost:3306/bpmsdb";
    private static final String DbUsername = "root";
    private static final String DbPassword = "";

 public void Connection() throws SQLException {
        try {
            Class.forName(DbDriver);
            con = DriverManager.getConnection(DbUrl, DbUsername, DbPassword);
            st = con.createStatement();
            if (con != null) {
                System.out.println("Connection Successfull");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegisterClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cUserName = new javax.swing.JTextField();
        cEmail1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cjPassword = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        Signup1 = new javax.swing.JButton();
        Signup = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Get Pretty Look");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Forte", 1, 33)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 102));
        jLabel2.setText("Input Client Account");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        cUserName.setForeground(new java.awt.Color(102, 102, 102));
        cUserName.setText("  USERNAME");
        cUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cUserName.setOpaque(true);
        cUserName.setSelectedTextColor(new java.awt.Color(255, 0, 0));
        cUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cUserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cUserNameFocusLost(evt);
            }
        });
        cUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(cUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 320, 40));
        cUserName.getAccessibleContext().setAccessibleName("");
        cUserName.getAccessibleContext().setAccessibleDescription("");

        cEmail1.setForeground(new java.awt.Color(102, 102, 102));
        cEmail1.setText("  EMAIL");
        cEmail1.setToolTipText("Enter Email");
        cEmail1.setActionCommand("<Not Set>");
        cEmail1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cEmail1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cEmail1.setName(""); // NOI18N
        cEmail1.setOpaque(true);
        cEmail1.setSelectedTextColor(new java.awt.Color(255, 51, 51));
        cEmail1.setSelectionColor(new java.awt.Color(0, 153, 204));
        cEmail1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cEmail1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cEmail1FocusLost(evt);
            }
        });
        cEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cEmail1ActionPerformed(evt);
            }
        });
        getContentPane().add(cEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 320, 40));

        jButton1.setBackground(new java.awt.Color(204, 0, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOG IN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 320, 40));

        cjPassword.setForeground(new java.awt.Color(102, 102, 102));
        cjPassword.setText("PASSWORD");
        cjPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cjPassword.setDropMode(javax.swing.DropMode.INSERT);
        cjPassword.setOpaque(true);
        cjPassword.setSelectedTextColor(new java.awt.Color(102, 0, 0));
        cjPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cjPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cjPasswordFocusLost(evt);
            }
        });
        cjPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(cjPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 320, 40));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox1.setText("See Password?");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 120, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Not Yet Registered?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, -1, -1));

        Signup1.setBackground(java.awt.Color.lightGray);
        Signup1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Signup1.setForeground(new java.awt.Color(51, 0, 153));
        Signup1.setText("Sign Up");
        Signup1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Signup1.setBorderPainted(false);
        Signup1.setContentAreaFilled(false);
        Signup1.setRolloverEnabled(false);
        Signup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Signup1ActionPerformed(evt);
            }
        });
        getContentPane().add(Signup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 70, 40));

        Signup.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Signup.setForeground(new java.awt.Color(255, 0, 153));
        Signup.setText("←");
        Signup.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 153), 2, true));
        Signup.setContentAreaFilled(false);
        Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupActionPerformed(evt);
            }
        });
        getContentPane().add(Signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, 210, 50));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Best Beauty expert at your home and provides beauty salon at home.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, 20));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Home Salon provide well trained beauty professionals for beauty");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, 20));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("services at home including Facial, Clean Up, Bleach, Waxing,Pedicure,");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, -1, 20));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Manicure, etc. Step into beauty and relaxation. Book an appointment");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, -1, 40));

        jLabel8.setBackground(new java.awt.Color(255, 255, 204));
        jLabel8.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("and experience the glam life at BGLAM Salon.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, -1, 20));

        jButton4.setBackground(new java.awt.Color(249, 156, 208));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("ADMIN");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.setFocusCycleRoot(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 40, 120, 30));

        jLabel9.setFont(new java.awt.Font("Forte", 1, 35)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CLIENT ACCOUNT");
        jLabel9.setToolTipText("");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gif4.gif"))); // NOI18N
        background1.setText("Best Beauty expert at your home and provides beauty salon at home.");
        background1.setToolTipText("");
        getContentPane().add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1180, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cUserNameActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
         if (jCheckBox1.isSelected()) {
            cjPassword.setEchoChar((char) 0); // Show password
        } else {
            cjPassword.setEchoChar('*'); // Mask password
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void Signup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Signup1ActionPerformed
        RegisterClient registeraclient = new RegisterClient();
        registeraclient.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Signup1ActionPerformed

    private void SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupActionPerformed
       RegisterClient registeraclient = new RegisterClient();
        registeraclient.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SignupActionPerformed

    private void cEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cEmail1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         Admin admin = new Admin();
        admin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    String email = cEmail1.getText().trim();
String password = new String(cjPassword.getPassword()).trim();

if (email.isEmpty() || password.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

try {
    String query = "SELECT * FROM tbclients WHERE Email = ?";
    pst = con.prepareStatement(query);
    pst.setString(1, email);
        ResultSet rs = pst.executeQuery();

    if (rs.next()) {
        String passDb = rs.getString("Password");
        String clientName = rs.getString("ClientName");

        if (password.equals(passDb)) {  // Use BCrypt for secure matching (if stored with hash)
            JOptionPane.showMessageDialog(this, "Welcome, " + clientName + "!", "Login Success", JOptionPane.INFORMATION_MESSAGE);
            ClientIndex clientindex = new ClientIndex();
            clientindex.setVisible(true);
            clientindex.pack();
            clientindex.setLocationRelativeTo(null);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Incorrect password!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "User not found!", "Error", JOptionPane.ERROR_MESSAGE);
    }

} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

// Clear fields
cEmail1.setText("");
cjPassword.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cEmail1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cEmail1FocusGained
         if (cEmail1.getText().equals("ENTER EMAIL")) {
            cEmail1.setText("ENTER EMAIL");
            cEmail1.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_cEmail1FocusGained

    private void cEmail1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cEmail1FocusLost
           if (cEmail1.getText().isEmpty()) {
            cEmail1.setText("ENTER EMAIL");
            cEmail1.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_cEmail1FocusLost

    private void cjPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cjPasswordFocusGained
            if (cjPassword.getText().equals("ENTER PASSWORD")) {
            cjPassword.setText("ENTER PASSWORD");
            cjPassword.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_cjPasswordFocusGained

    private void cjPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cjPasswordFocusLost
            if (cjPassword.getText().isEmpty()) {
            cjPassword.setText("ENTER PASSWORD");
            cjPassword.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_cjPasswordFocusLost

    private void cUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cUserNameFocusGained
        if (cUserName.getText().equals("ENTER USERNAME")) {
            cUserName.setText("ENTER USERNAME");
            cUserName.setForeground(new Color(0, 0, 0));
        
    }//GEN-LAST:event_cUserNameFocusGained
}
    private void cUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cUserNameFocusLost
           if (cUserName.getText().isEmpty()) {
            cUserName.setText("USERNAME");
            cUserName.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_cUserNameFocusLost

    private void cjPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjPasswordActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Client().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Signup;
    private javax.swing.JButton Signup1;
    private javax.swing.JLabel background1;
    private javax.swing.JTextField cEmail1;
    private javax.swing.JTextField cUserName;
    private javax.swing.JPasswordField cjPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

  
    
}

