/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BeautySalon;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author effel joy alquizar
 */
public class RegisterClient extends javax.swing.JFrame {

    /**
     * Creates new form RegisterClient
     */
    public RegisterClient() {
       initComponents();
       Image img = new ImageIcon(getClass().getResource("/images/logo.jpg")).getImage();
    
    // Set the icon image for the JFrame
    this.setIconImage(img);
        try {
            Connection();
        } catch (SQLException ex) {
            Logger.getLogger(RegisterClient.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setLocationRelativeTo(null);
    }
    Connection con;
    Statement st;
    PreparedStatement pst;
    private static final String DbName = "bpmsdb";
    private static final String DbDriver = "com.mysql.cj.jdbc.Driver";
    private static final String DbUrl = "jdbc:mysql://localhost:3306/bpmsdb";
    private static final String DbUsername = "root";
    private static final String DbPassword = "";
  

public void Connection() throws SQLException {
        try {
            Class.forName(DbDriver);
            con = DriverManager.getConnection(DbUrl, DbUsername, DbPassword);
            st = con.createStatement();
            if (con != null) {
                System.out.println("Connection Successfull");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegisterClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ClientUser = new javax.swing.JTextField();
        NumberClient = new javax.swing.JTextField();
        Email1 = new javax.swing.JTextField();
        ClientPass = new javax.swing.JPasswordField();
        showpassclient = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1bacgroun2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 153));
        jLabel2.setText("A Beauty Salon");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("This parlour provides huge facilities with advanced technology");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("equipment and the best quality service.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Here we offer the best treatment that you");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, 20));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 153));
        jButton1.setText("→ ");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 153), 2, true));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 190, 50));

        jLabel6.setFont(new java.awt.Font("Forte", 0, 35)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 102));
        jLabel6.setText("Create Client Account");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, -1, 50));

        ClientUser.setForeground(new java.awt.Color(102, 102, 102));
        ClientUser.setText("  Username");
        ClientUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 1, true));
        ClientUser.setSelectedTextColor(new java.awt.Color(204, 0, 0));
        ClientUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ClientUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ClientUserFocusLost(evt);
            }
        });
        getContentPane().add(ClientUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 310, 40));

        NumberClient.setForeground(new java.awt.Color(102, 102, 102));
        NumberClient.setText("  Number");
        NumberClient.setAutoscrolls(false);
        NumberClient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 1, true));
        NumberClient.setSelectedTextColor(new java.awt.Color(204, 0, 0));
        NumberClient.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NumberClientFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NumberClientFocusLost(evt);
            }
        });
        NumberClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberClientActionPerformed(evt);
            }
        });
        getContentPane().add(NumberClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 310, 40));

        Email1.setForeground(new java.awt.Color(102, 102, 102));
        Email1.setText("  Email");
        Email1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 1, true));
        Email1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Email1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Email1FocusLost(evt);
            }
        });
        Email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email1ActionPerformed(evt);
            }
        });
        getContentPane().add(Email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 310, 40));

        ClientPass.setForeground(new java.awt.Color(102, 102, 102));
        ClientPass.setText("jPasswordField1");
        ClientPass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 1, true));
        ClientPass.setSelectedTextColor(new java.awt.Color(204, 0, 0));
        ClientPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientPassActionPerformed(evt);
            }
        });
        getContentPane().add(ClientPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 310, 40));

        showpassclient.setForeground(new java.awt.Color(102, 102, 102));
        showpassclient.setText("jPasswordField2");
        showpassclient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 1, true));
        showpassclient.setSelectedTextColor(new java.awt.Color(204, 0, 0));
        showpassclient.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                showpassclientFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                showpassclientFocusLost(evt);
            }
        });
        showpassclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassclientActionPerformed(evt);
            }
        });
        getContentPane().add(showpassclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 310, 40));

        jButton2.setBackground(new java.awt.Color(204, 0, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SIGN UP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, 310, 40));

        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ADMIN");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 120, 30));

        jLabel7.setFont(new java.awt.Font("Forte", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("REGISTER CLIENT");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jCheckBox1.setText("See Password?");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, -1, -1));

        jCheckBox2.setText("See Password?");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Already Registered?");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, 130, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 204));
        jButton4.setText("Log In");
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 530, 80, 20));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" Book your next appointment today and discover the difference");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        jLabel10.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" might have never experienced before");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        jLabel1bacgroun2.setFont(new java.awt.Font("Forte", 0, 30)); // NOI18N
        jLabel1bacgroun2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1bacgroun2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rgif1.gif"))); // NOI18N
        getContentPane().add(jLabel1bacgroun2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Client client = new Client();
        client.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Admin admin = new Admin();
        admin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Client client = new Client();
        client.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email1ActionPerformed
  
    }//GEN-LAST:event_Email1ActionPerformed
    
    private void NumberClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberClientActionPerformed

    private void ClientUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ClientUserFocusLost
            if (ClientUser.getText().isEmpty()) {
            ClientUser.setText("USERNAME");
             ClientUser.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_ClientUserFocusLost

    private void ClientUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ClientUserFocusGained
        if (ClientUser.getText().equals("USERNAME")) {
            ClientUser.setText("");
            ClientUser.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_ClientUserFocusGained
    }
    private void Email1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email1FocusLost
             if (Email1.getText().isEmpty()) {
           Email1.setText("ENTER EMAIL");
             Email1.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_Email1FocusLost

    private void Email1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Email1FocusGained
        if (Email1.getText().equals("USERNAME")) {
           Email1.setText("");
            Email1.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_Email1FocusGained
    }
    private void NumberClientFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NumberClientFocusGained
           if (NumberClient.getText().equals("MOBILE NUMBER")) {
        NumberClient.setText("");
        NumberClient.setForeground(new Color(0, 0, 0));
    }

    }//GEN-LAST:event_NumberClientFocusGained

    private void NumberClientFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NumberClientFocusLost
        if (NumberClient.getText().isEmpty()) {
        NumberClient.setText("MOBILE NUMBER");
        NumberClient.setForeground(new Color(153, 153, 153));
    }
    }//GEN-LAST:event_NumberClientFocusLost

    private void showpassclientFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_showpassclientFocusGained
        if (showpassclient.getText().equals("MOBILE NUMBER")) {
      showpassclient.setText("");
        showpassclient.setForeground(new Color(0, 0, 0));
    }
    }//GEN-LAST:event_showpassclientFocusGained

    private void showpassclientFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_showpassclientFocusLost
          if (showpassclient.getText().isEmpty()) {
        showpassclient.setText("MOBILE NUMBER");
        showpassclient.setForeground(new Color(153, 153, 153));
    }
    }//GEN-LAST:event_showpassclientFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String clientName = ClientUser.getText().trim();
    String email = Email1.getText().trim();
    String password = new String(showpassclient.getPassword()).trim();
    String number = NumberClient.getText().trim();

    if (clientName.equals("") || email.equals("") || password.equals("") || number.equals("")) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!number.matches("\\d{11}")) {
        JOptionPane.showMessageDialog(this, "Mobile number must be 11 digits", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        String insertQuery = "INSERT INTO tbclients (ClientName, Email, Password, MobileNumber) VALUES (?, ?, ?, ?)";
        pst = con.prepareStatement(insertQuery);
        pst.setString(1, clientName);
        pst.setString(2, email);
        pst.setString(3, password);
        pst.setString(4, number);

        int rowsInserted = pst.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Registered Successfully!");
            ClientUser.setText("USERNAME");
            Email1.setText("EMAIL");
            showpassclient.setText("");
            NumberClient.setText("MOBILE NUMBER");
            Client client = new Client();
            client.setVisible(true);
            client.pack();
            client.setLocationRelativeTo(null);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Registration failed!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void ClientPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientPassActionPerformed

    private void showpassclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassclientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showpassclientActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
              if (jCheckBox1.isSelected()) {
        ClientPass.setEchoChar((char) 0);
    } else {
        ClientPass.setEchoChar('•'); // Or showpassadmin1.getEchoChar() from init
    }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
                  if (jCheckBox2.isSelected()) {
        showpassclient.setEchoChar((char) 0);
    } else {
        showpassclient.setEchoChar('•'); // Or showpassadmin1.getEchoChar() from init
    }
    }//GEN-LAST:event_jCheckBox2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ClientPass;
    private javax.swing.JTextField ClientUser;
    private javax.swing.JTextField Email1;
    private javax.swing.JTextField NumberClient;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel1bacgroun2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField showpassclient;
    // End of variables declaration//GEN-END:variables
}
