/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BeautySalon;

import java.awt.Image;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Connection;
import javax.swing.ImageIcon;
/**
 *
 * @author effel joy alquizar
 */
public class RegisterAdmin extends javax.swing.JFrame {
Connection con;
    Statement st;
    PreparedStatement pst;
    /**
     * Creates new form RegisterAdmin
     */
    public RegisterAdmin() {
        initComponents();
        Image img = new ImageIcon(getClass().getResource("/images/logo.jpg")).getImage();
    
    // Set the icon image for the JFrame
    this.setIconImage(img);
        try {
            Connection();
        } catch (SQLException ex) {
            Logger.getLogger(RegisterClient.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setLocationRelativeTo(null);
    }
    
    
    private static final String DbName = "bpmsdb";
    private static final String DbDriver = "com.mysql.cj.jdbc.Driver";
    private static final String DbUrl = "jdbc:mysql://localhost:3306/bpmsdb";
    private static final String DbUsername = "root";
    private static final String DbPassword = "";
  

public void Connection() throws SQLException {
        try {
            Class.forName(DbDriver);
           con = DriverManager.getConnection(DbUrl, DbUsername, DbPassword);
            st = con.createStatement();
            if (con != null) {
                System.out.println("Connection Successfull");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegisterClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AdminUser = new javax.swing.JTextField();
        NumberAdmin = new javax.swing.JTextField();
        Email1 = new javax.swing.JTextField();
        showpassadmin1 = new javax.swing.JPasswordField();
        showpassadmin2 = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        backgroun4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Forte", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTER ADMIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 380, -1));

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CLIENT");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 40, 110, 30));

        jLabel2.setFont(new java.awt.Font("Forte", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 102));
        jLabel2.setText("Create Admin Account");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 360, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 153));
        jLabel3.setText("Get Pretty Look");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 390, -1));

        AdminUser.setForeground(new java.awt.Color(102, 102, 102));
        AdminUser.setText("  Username");
        AdminUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        getContentPane().add(AdminUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 290, 40));

        NumberAdmin.setForeground(new java.awt.Color(102, 102, 102));
        NumberAdmin.setText("  Number");
        NumberAdmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 51), 1, true));
        getContentPane().add(NumberAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 290, 40));

        Email1.setForeground(new java.awt.Color(102, 102, 102));
        Email1.setText("  Email");
        Email1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        getContentPane().add(Email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 290, 290, 40));

        showpassadmin1.setForeground(new java.awt.Color(102, 102, 102));
        showpassadmin1.setText("jPasswordField1");
        showpassadmin1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));
        showpassadmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassadmin1ActionPerformed(evt);
            }
        });
        getContentPane().add(showpassadmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 290, 40));

        showpassadmin2.setForeground(new java.awt.Color(102, 102, 102));
        showpassadmin2.setText("jPasswordField2");
        showpassadmin2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));
        showpassadmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassadmin2ActionPerformed(evt);
            }
        });
        getContentPane().add(showpassadmin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, 290, 40));

        jCheckBox1.setText("See Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, -1, -1));

        jCheckBox2.setText("See Password?");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 0, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SIGN UP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 482, 290, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Already Registered?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 530, 130, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 102));
        jButton3.setText("Log In");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(872, 526, 80, 30));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Best Beauty expert at your home and provides beauty salon at");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 420, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("home. Home Salon provide well trained beauty professionals");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 520, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("for beauty services at home including Facial, Clean Up, Bleach,");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 500, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Waxing,Pedicure, Manicure, etc. Step into beauty and relaxation.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 500, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 153));
        jButton4.setText("→ ");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 153), 2, true));
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 190, 50));

        backgroun4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gif8.gif"))); // NOI18N
        backgroun4.setText("jLabel9");
        getContentPane().add(backgroun4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1190, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
          if (jCheckBox1.isSelected()) {
        showpassadmin1.setEchoChar((char) 0);
    } else {
        showpassadmin1.setEchoChar('•'); // Or showpassadmin1.getEchoChar() from init
    }

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void showpassadmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassadmin1ActionPerformed


    }//GEN-LAST:event_showpassadmin1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Admin admin = new Admin();
        admin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      Admin admin = new Admin();
        admin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Client client = new Client();
        client.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String AdminName = AdminUser.getText().trim();
    String email = Email1.getText().trim();
    String password = new String(showpassadmin1.getPassword()).trim();
    String number = NumberAdmin.getText().trim();

    if (AdminName.equals("") || email.equals("") || password.equals("") || number.equals("")) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!number.matches("\\d{11}")) {
        JOptionPane.showMessageDialog(this, "Mobile number must be 11 digits", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        String insertQuery = "INSERT INTO tbladmin (AdminName, Email, Password, MobileNumber) VALUES (?, ?, ?, ?)";
        pst = con.prepareStatement(insertQuery);
        pst.setString(1, AdminName);
        pst.setString(2, email);
        pst.setString(3, password);
        pst.setString(4, number);

        int rowsInserted = pst.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Registered Successfully!Proceed to AdminLogin");
            AdminUser.setText("USERNAME");
            Email1.setText("EMAIL");
            showpassadmin1.setText("");
            NumberAdmin.setText("MOBILE NUMBER");
            Admin admin = new Admin();
            admin.setVisible(true);
            admin.pack();
            admin.setLocationRelativeTo(null);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Registration failed!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void showpassadmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassadmin2ActionPerformed
                String confirmPassword = new String(showpassadmin2.getPassword()).trim();
if (!showpassadmin1.equals(confirmPassword)) {
    JOptionPane.showMessageDialog(this, "Passwords do not match", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}
    }//GEN-LAST:event_showpassadmin2ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
         if (jCheckBox2.isSelected()) {
        showpassadmin2.setEchoChar((char) 0);
    } else {
        showpassadmin2.setEchoChar('•');
    }

    }//GEN-LAST:event_jCheckBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdminUser;
    private javax.swing.JTextField Email1;
    private javax.swing.JTextField NumberAdmin;
    private javax.swing.JLabel backgroun4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField showpassadmin1;
    private javax.swing.JPasswordField showpassadmin2;
    // End of variables declaration//GEN-END:variables
}
